version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Suppress all Dependabot PRs (including security updates) for the docs site, since it's statically generated
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "yearly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "yearly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
